services:
  server:
    image: text-extract-image
    container_name: text-extract-container
    build:
      context: .
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./requirements.txt
